### ISSUE TITLE
El score total de los players debería de guardarse en el Turn del Match cada vez que un Game finalice

### ISSUE THREAD

**Issue by Virako** [USantaTecla-game-backgammon/backgammon#34]
Al tener ahora los Turn que crean los Player, los Player ya no son los mismos como antes, y tendremos muchos players diferentes, con sus puntuaciones.

Tiene lo bueno de que tendremos cuanta puntuación han ganado en cada juego, pero cuando termine el juego, para tener un score total, tendremos que guardar la puntuación que ha obtenido el Player con Color X, en el match.turn con Color X

**Comment by leohakim** [comment]
Se soluciono con el nuevo método de Turn:

`def give_score(self) -> None:
        score = self.current_score()
        if self.last_game.board.is_all_pieces_off_board(Color.BLACK):
            self.turn.give_score(score, Color.BLACK)
            self.last_game.turn.give_score(score, Color.BLACK)

        if self.last_game.board.is_all_pieces_off_board(Color.RED):
            self.turn.give_score(score, Color.RED)
            self.last_game.turn.give_score(score, Color.RED)`
